- name: Rezilion
  uses: Rezilion/github-action@v2.3.0
name: test
on: [push]
jobs:
test_sanity:
  runs-on: ubuntu-latest
  container:
    image: nginx:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/Rezilion
    with:
      mode: start
      image_name: nginx:latest
      command: sleep 5
      env:
        REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
