name: CI
on: [push]
jobs:
  test-sanity:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
 
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.7.0 
        with:
          mode: 'start'
          image_name: 'python:3.7'
          command: 'sleep 5'
          
      - uses: Rezilion/github-action@v2.7.0 
        with:
          mode: 'start'
          image_name: 'python:3.7'
          command: 'echo "Hey"'
      
  Rezilion:
    needs: [test-sanity]
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_DONT_RUN_REMEDIATE: false
    steps:
      - uses: actions/checkout@v3
     # - uses: ./.github/actions/Rezilion #example using the private action
      - uses: Rezilion/github-action@v2.7.0 
        with:
          mode: 'validate'
              
  
