name: test
on: [push]
jobs:
  test_runtimes:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/n1j6b8j1/temp_runtimes:latest
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}      
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: "^main$"
      REZILION_REMEDIATE_CONFIG: "critical:all, high:all, medium:exploitable"
      # REZILION_SEVERITY_GATE: "critical"

      
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@2.15.0
        with:
          image_name: 'public.ecr.aws/n1j6b8j1/temp_runtimes:latest'
          mode: 'sca'

          command: |
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            python3 -c "from PIL import Image;import time;time.sleep(5) ; print(\"Hey\")"
            timeout 5 sh /sh_script_with_extension.sh || true
            timeout 5 perl /perl_script_with_extension.pl || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            timeout 5 node /my_app/index.js || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            timeout 5 node /node_script_test.js || true
            timeout 5 dotnet exec /NetCore_evl/LoadDLL.dll || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            timeout -s 9 5 /Net5/bin/Debug/net5.0/LoadDLL || true
            timeout -s 9 5 ruby /load_packages.rb || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true

  test_webgoat:
    runs-on: ubuntu-latest
    container:
      image: webgoat/webgoat:latest
      options: --user root
    env:
     REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
     REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
     REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
     REZILION_BRANCH_NAME_UPLOADING_REGEX: "^main$"

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@2.15.0
      
        with:
          image_name: 'webgoat/webgoat:latest'
          mode: 'sca'
          
          command: |
            cd /home/webgoat
            timeout 40 java -Duser.home=/home/webgoat -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -Dwebgoat.host=0.0.0.0 -Dwebwolf.host=0.0.0.0 -Dwebgoat.port=8080 -Dwebwolf.port=9090 -jar webgoat.jar || true

  rezilion:
    needs: [test_runtimes, test_webgoat]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:136993c0

    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$
      REZILION_REMEDIATE_CONFIG: "critical:all, high:all, medium:exploitable"

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@2.15.0
        with:
          mode: 'validate'
