name: test
on: [push]
jobs:
  test_runtimes:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/n1j6b8j1/temp_runtimes:latest
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.13.3
        with:
          image_name: 'public.ecr.aws/n1j6b8j1/temp_runtimes:latest'
          mode: 'start'

          command: |
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            python3 -c "from PIL import Image;import time;time.sleep(5) ; print(\"Hey\")"
            timeout 5 sh /sh_script_with_extension.sh || true
            timeout 5 perl /perl_script_with_extension.pl || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            timeout 5 node /my_app/index.js || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            timeout 5 node /node_script_test.js || true
            timeout 5 dotnet exec /NetCore_evl/LoadDLL.dll || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true
            timeout -s 9 5 /Net5/bin/Debug/net5.0/LoadDLL || true
            timeout -s 9 5 ruby /load_packages.rb || true
            timeout 10 /usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar /test-war-java-11.war --httpPort=4444 || true

  test_redis:
    runs-on: ubuntu-latest
    container:
      image: redis:7.0.4
    env:
     REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
     REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.13.3


        with:
          image_name: 'redis:7.0.4'
          mode: 'start'
          
          command: |
            timeout 10 redis-server || true

  rezilion:
    needs: [test_runtimes, test_redis]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:b22238db

    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
      REZILION_RUN_REMEDIATE: true
      REZILION_API_KEY: ${{ secrets.REZILION_API_KEY }}
      REZILION_BRANCH_NAME_UPLOADING_REGEX: ^main$

    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.13.3
        with:
          mode: 'validate'
