name: CI
on: [push]
jobs:
  test_runtimes:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
 
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: export
      - uses: Rezilion/github-action@v2.5.1 
        with:
          image_name: 'python:3.7'
          mode: 'start'
          command: python3 -c "import time; time.sleep(5) ; print(\"Hey\")"
      
  Rezilion:
    needs: [test_runtimes]
    runs-on: ubuntu-latest
    container:
      image: rezilion/validate-ci:b63c85d0
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
#      REZILION_SEVERITY_GATE: "critical"
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.5.1 
        with:
          mode: 'validate'
              
      
  
