name: CI
on: [push]
jobs:
  test-sanity:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
 
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.7.0 #example using the public action
        with:
          mode: 'start'
          image_name: 'nginx:latest'
          command: 'sleep 5'
      
  Rezilion:
    needs: [test-sanity]
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/Rezilion #example using the private action
        with:
          mode: 'validate'
              
      
  
