name: CI
on: [push]
jobs:
  test-sanity:
    runs-on: ubuntu-latest
    container:
      image: vulhub/flask:1.1.1
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
 
    steps:
      - uses: actions/checkout@v3
      - uses: Rezilion/github-action@v2.5.1 #example using the public action
        with:
          mode: 'start'
          image_name: 'vulhub/flask:1.1.1'
          command: 'echo "Hello world"; /usr/local/bin/flask --help; sleep 5'
      
  Rezilion:
    needs: [test-sanity]
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
    env:
      REZILION_LICENSE_KEY: ${{ secrets.REZILION_LICENSE_KEY }}
      REZILION_ACCESS_TOKEN: ${{ secrets.REZILION_ACCESS_TOKEN }}
#      REZILION_SEVERITY_GATE: "critical"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/Rezilion #example using the private action
        with:
          mode: 'validate'
              
      
  
